---
- name: "Update apt cache"
  ansible.builtin.apt:
    update_cache: true

- name: "Default to stable repo"
  ansible.builtin.copy:
    src: "preference_debian_stable"
    dest: "/etc/apt/preferences.d/debian_stable"
    owner: 'root'
    group: 'root'
    mode: '0644'

- name: "Enable backports repo"
  ansible.builtin.template:
    src: "backports-{{ ansible_os_family }}.list.j2"
    dest: "/etc/apt/sources.list.d/{{ backport_repo_name }}.list"
    owner: 'root'
    group: 'root'
    mode: '0644'
  when: use_debian_backports|bool

- name: "Disable backports repo"
  ansible.builtin.file:
    path: "/etc/apt/sources.list.d/{{ backport_repo_name }}.list"
    state: absent
  when: not use_debian_backports|bool

- name: "Enable testing repo"
  ansible.builtin.template:
    src: "debian_testing_source.list.j2"
    dest: "/etc/apt/sources.list.d/debian_testing_source.list"
    owner: 'root'
    group: 'root'
    mode: '0644'
  when: debian_fallback_to_testing|bool

- name: "Disable testing repo"
  ansible.builtin.file:
    path: "/etc/apt/sources.list.d/debian_testing_source.list"
    state: absent
  when: not debian_fallback_to_testing|bool

- name: "Fallback to testing repo"
  ansible.builtin.copy:
    src: "preference_debian_testing"
    dest: "/etc/apt/preferences.d/debian_testing"
    owner: 'root'
    group: 'root'
    mode: '0644'
  when: debian_fallback_to_testing|bool

- name: "Disable fallback to testing repo"
  ansible.builtin.file:
    path: "/etc/apt/preferences.d/debian_testing"
    state: absent
  when: not debian_fallback_to_testing|bool

- name: "Enable unstable repo"
  ansible.builtin.template:
    src: "debian_unstable_source.list.j2"
    dest: "/etc/apt/sources.list.d/debian_unstable_source.list"
    owner: 'root'
    group: 'root'
    mode: '0644'
  when: debian_fallback_to_unstable|bool

- name: "Disable unstable repo"
  ansible.builtin.file:
    path: "/etc/apt/sources.list.d/debian_unstable_source.list"
    state: absent
  when: not debian_fallback_to_unstable|bool

- name: "Fallback to unstable repo"
  ansible.builtin.copy:
    src: "preference_debian_unstable"
    dest: "/etc/apt/preferences.d/debian_unstable"
    owner: 'root'
    group: 'root'
    mode: '0644'
  when: debian_fallback_to_unstable|bool

- name: "Disable fallback to unstable repo"
  ansible.builtin.file:
    path: "/etc/apt/preferences.d/debian_unstable"
    state: absent
  when: not debian_fallback_to_unstable|bool

- name: "Ensure unwanted packages are absent"
  ansible.builtin.apt:
    name: "{{ pkglist_absent }}"
    update_cache: false
    autoremove: true
    state: absent
    purge: false

- name: "Install required packages"
  ansible.builtin.apt:
    name: "{{ pkglist }}"
    update_cache: true
    autoremove: true
    state: present

- name: "Install required backport packages"
  ansible.builtin.apt:
    name: "{{ backport_pkglist }}"
    default_release: "{{ backport_repo_name }}"
    update_cache: true
    autoremove: true
    state: latest
  when: use_debian_backports and backport_pkglist is defined

- name: select default locale
  ansible.builtin.debconf:
    name: locales
    question: locales/default_environment_locale
    value: '{{ debian_default_locale }}'
    vtype: select
  changed_when: false

- name: /etc/locale.gen
  ansible.builtin.lineinfile:
    dest: /etc/locale.gen
    regexp: '^#? ?{{ item.value }}'
    line: '{{ item.value }}'
    state: "{{ item.state }}"
    create: true
    owner: 'root'
    group: 'root'
    mode: '0644'
  loop: "{{ debian_locales }}"
  changed_when: false

- name: rebuild debian locales database
  ansible.builtin.command: "{{ item }}"
  changed_when: false
  with_items:
    - dpkg-reconfigure locales -f noninteractive
    - /usr/sbin/locale-gen
