---
- name: "Include os specific variables"
  include_vars: "packages-{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
- name: "Call install-packages task for RedHat like systems"
  include_tasks: install-packages-RedHat.yml
  when: ansible_os_family == "RedHat"
- name: "Call install-packages task for Debian like systems"
  include_tasks: install-packages-Debian.yml
  when: ansible_os_family == "Debian"
- name: "Tuned history format for Bourne compatible shells (bash, ksh, ash)"
  copy:
    content: 'export HISTTIMEFORMAT="%F %T "'
    dest: '/etc/profile.d/history-timeformat.sh'
    owner: root
    group: root
    mode: '0644'
- name: "Configure journal forwarding to syslog"
  lineinfile:
    path: /etc/systemd/journald.conf
    regexp: '^ForwardToSyslog='
    line: "ForwardToSyslog={{ journal_forward_to_syslog }}"
    owner: root
    group: root
    mode: '0644'

- name: select default locale
  debconf:
    name: locales
    question: locales/default_environment_locale
    value: '{{ item.value }}'
    vtype: select
  loop: "{{ debian_default_locale }}"
  when: ansible_os_family == "Debian"

- name: rebuild debian locales database
  command: "{{ item }}"
  with_items:
    - dpkg-reconfigure locales -f noninteractive
    - /usr/sbin/locale-gen

- name: /etc/locale.gen
  lineinfile:
    dest: /etc/locale.gen
    regexp: '^#? ?{{ item.value }}'
    line: '{{ item.value }}'
    state: "{{ item.state }}"
  loop: "{{ debian_locales }}"
  when: ansible_os_family == "Debian"

- name: rebuild debian locales database
  command: "{{ item }}"
  with_items:
    - dpkg-reconfigure locales -f noninteractive
    - /usr/sbin/locale-gen

- name: Configure locale to '{{ debian_lc_locale }}'
  command: "localectl set-locale LC_ALL={{ debian_lc_locale }}"
  changed_when: false
  when: ansible_os_family == "Debian"
...
