---
- name: Converge
  hosts: all
  connection: local
  become: true
  vars:
    debian_fallback_to_unstable: true
    debian_fallback_to_testing: true
  roles:
    - role: "infra_monkey.base_system"
    # - role: freeipa.ansible_freeipa.ipaclient
