---
- name: Converge
  hosts: all
  connection: local
  become: true
  vars:
    debian_fallback_to_unstable: false
    debian_fallback_to_testing: false
  roles:
    - role: "ansible_role_base_system"
