---
- name: Converge
  hosts: all
  connection: local
  become: true
  vars:
    debian_fallback_to_unstable: false
    debian_fallback_to_testing: false
  roles:
    - role: "base_system"
    #- role: "infra_monkey.base_system"
    # - role: freeipa.ansible_freeipa.ipaclient
