---
- name: Converge
  hosts: all
  connection: local
  become: true
  # dependency:
  #   name: galaxy
  #   options:
  #     requirements-file: collections.yml
  vars:
    debian_fallback_to_unstable: true
    debian_fallback_to_testing: true
  collections:
    - freeipa.ansible_freeipa
  roles:
    - role: "infra_monkey.base_system"
    - role: ipaclient
