---
- name: Prepare
  hosts: all
  connection: local
  become: true
  tasks:
    - block:
        - name: "Update distribution"
          apt:
            upgrade: dist
            update_cache: true
        - name: "Install required packages"
          apt:
            name: "apt-utils"
            update_cache: true
      when: ansible_os_family == "Debian"
