---
- name: Prepare
  hosts: all
  connection: local
  become: true
  tasks:
    - block:
      - name: "Update apt cache"
        apt:
          upgrade: dist
          update_cache: true
    when: ansible_os_family == "Debian"